# Generated by Django 5.1.1 on 2024-09-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='friends_request',
            new_name='friends_req_receive_8908e9_idx',
            old_name='friends_fri_receive_0a1ec1_idx',
        ),
        migrations.RenameIndex(
            model_name='friends_request',
            new_name='friends_req_sender__1d1720_idx',
            old_name='friends_fri_sender__5008a5_idx',
        ),
        migrations.AlterModelTable(
            name='friends_request',
            table='friends_request',
        ),
        migrations.AlterModelTable(
            name='user_activity',
            table='friends_users_activity',
        ),
    ]
