# Generated by Django 5.1.1 on 2024-09-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_rename_friends_fri_receive_0a1ec1_idx_friends_req_receive_8908e9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends_request',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
