# Generated by Django 5.1.1 on 2024-09-25 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_alter_friends_request_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends_request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 19, 2, 30, 25959, tzinfo=datetime.timezone.utc)),
        ),
    ]
