# Generated by Django 5.1.1 on 2024-09-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_alter_friends_request_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends_request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
